# SPDX-FileCopyrightText: © 2026 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

hazzuk_core_traefik_enabled: false

hazzuk_core_traefik_stack_defaults:
  traefik:
    image: docker.io/traefik # -8<- [end:x]
    version: v3.7.13@sha256:f86a2cab1b5c649070c49f883c743dd32d8485a56e3368c5f93b9e91f1e91259 # -8<- [end:x]
    log_level: debug # trace, debug, info, warn, error, fatal, panic
    acme_staging_enabled: true
    acme_email: cert@example.com
    acme_staging_ca_server_url: "https://acme-staging-v02.api.letsencrypt.org/directory" # -8<- [end:x]
    acme_live_ca_server_url: "https://acme-v02.api.letsencrypt.org/directory" # "https://acme.zerossl.com/v2/DV90" # -8<- [end:x]
    dashboard_enabled: true
    dashboard_forward_auth_enabled: true
    dashboard_domain: "traefik.{{ karo_compose_root_domain }}"
    custom_domains_raw: |
      # - main: "*.int.{{ karo_compose_root_domain }}"
    secrets:
      acme_zone_api_token: "" # cloudflare
      acme_dns_api_token: "" # cloudflare
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth # -8<- [end:x]
    version: v5.2.0-distroless@sha256:aff752a57511f9346109b4d427c132db71dfa480138698e1f42feaf335f7cda9 # -8<- [end:x]
    domain: "tinyauth.{{ karo_compose_root_domain }}"
    log_level: info # trace, debug, info, warn, error, fatal, panic
    oidc_client_id: ""
    secrets:
      oidc_client_secret: ""
  cetusguard:
    image: docker.io/hectorm/cetusguard # -8<- [end:x]
    version: v1.1.4@sha256:16a60a57943bb5ba4c3792c6b815cfb180f3492a7cabc469036ac1291c9c5365 # -8<- [end:x]
    log_level: 6 # 0-7 (min to max verbosity)
